name = "resume-page"
main = "src/worker.ts"
compatibility_date = "2025-08-25"

[build]
command = "npm run build"

[assets]
directory = "./dist"
binding = "ASSETS"

# Email configuration via environment variables for local development (.dev.vars)
# For production deployment, use secrets:
# wrangler secret put TO_EMAIL
# wrangler secret put FROM_EMAIL  
# wrangler secret put FROM_NAME
# wrangler secret put RESEND_API_KEY
